#############################################################################
# Makefile for building: ModbusTest
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  ModbusTest.pro
# Template: app
# Command: /home/tommy/raspi/qt5/bin/qmake -o Makefile ModbusTest.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /opt/cross-pi-gcc/bin/arm-linux-gnueabihf-gcc
CXX           = /opt/cross-pi-gcc/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/tommy/raspi/sysroot -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/tommy/raspi/sysroot -O2 -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/tommy/raspi/qt5pi/include -I/home/tommy/raspi/qt5pi/include/QtNetwork -I/home/tommy/raspi/qt5pi/include/QtCore -I. -I/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++
QMAKE         = /home/tommy/raspi/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/tommy/raspi/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/tommy/raspi/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ModbusTest1.0.0
DISTDIR = /mnt/d/_Work/ModbusTest/.tmp/ModbusTest1.0.0
LINK          = /opt/cross-pi-gcc/bin/arm-linux-gnueabihf-g++
LFLAGS        = -mfloat-abi=hard --sysroot=/home/tommy/raspi/sysroot -Wl,-O1 -Wl,-rpath,/usr/local/qt5pi/lib -Wl,-rpath-link,/home/tommy/raspi/sysroot/opt/vc/lib -Wl,-rpath-link,/home/tommy/raspi/sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link,/home/tommy/raspi/sysroot/lib/arm-linux-gnueabihf
LIBS          = $(SUBLIBS) /home/tommy/raspi/qt5pi/lib/libQt5Network.so /home/tommy/raspi/qt5pi/lib/libQt5Core.so -lpthread   
AR            = /opt/cross-pi-gcc/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = 
SED           = sed
STRIP         = /opt/cross-pi-gcc/bin/arm-linux-gnueabihf-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = helpers.cpp \
		main.cpp \
		modbus.cpp \
		modbusbase.cpp \
		modbusdatatable.cpp \
		modbushandler.cpp \
		modbusmaster.cpp \
		modbusslave.cpp moc_modbus.cpp \
		moc_modbusbase.cpp \
		moc_modbusdatatable.cpp \
		moc_modbushandler.cpp \
		moc_modbusslave.cpp
OBJECTS       = helpers.o \
		main.o \
		modbus.o \
		modbusbase.o \
		modbusdatatable.o \
		modbushandler.o \
		modbusmaster.o \
		modbusslave.o \
		moc_modbus.o \
		moc_modbusbase.o \
		moc_modbusdatatable.o \
		moc_modbushandler.o \
		moc_modbusslave.o
DIST          = /home/tommy/raspi/qt5/mkspecs/features/spec_pre.prf \
		/home/tommy/raspi/qt5/mkspecs/common/unix.conf \
		/home/tommy/raspi/qt5/mkspecs/common/linux.conf \
		/home/tommy/raspi/qt5/mkspecs/common/sanitize.conf \
		/home/tommy/raspi/qt5/mkspecs/common/gcc-base.conf \
		/home/tommy/raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		/home/tommy/raspi/qt5/mkspecs/common/g++-base.conf \
		/home/tommy/raspi/qt5/mkspecs/common/g++-unix.conf \
		/home/tommy/raspi/qt5/mkspecs/qdevice.pri \
		/home/tommy/raspi/qt5/mkspecs/features/device_config.prf \
		/home/tommy/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/home/tommy/raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		/home/tommy/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/home/tommy/raspi/qt5/mkspecs/qconfig.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_freetype.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_libjpeg.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_libpng.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/tommy/raspi/qt5/mkspecs/features/qt_functions.prf \
		/home/tommy/raspi/qt5/mkspecs/features/qt_config.prf \
		/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/home/tommy/raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/tommy/raspi/qt5/mkspecs/features/exclusive_builds.prf \
		/home/tommy/raspi/qt5/mkspecs/features/toolchain.prf \
		/home/tommy/raspi/qt5/mkspecs/features/default_pre.prf \
		/home/tommy/raspi/qt5/mkspecs/features/resolve_config.prf \
		/home/tommy/raspi/qt5/mkspecs/features/default_post.prf \
		/home/tommy/raspi/qt5/mkspecs/features/warn_on.prf \
		/home/tommy/raspi/qt5/mkspecs/features/qt.prf \
		/home/tommy/raspi/qt5/mkspecs/features/resources_functions.prf \
		/home/tommy/raspi/qt5/mkspecs/features/resources.prf \
		/home/tommy/raspi/qt5/mkspecs/features/moc.prf \
		/home/tommy/raspi/qt5/mkspecs/features/unix/thread.prf \
		/home/tommy/raspi/qt5/mkspecs/features/qmake_use.prf \
		/home/tommy/raspi/qt5/mkspecs/features/file_copies.prf \
		/home/tommy/raspi/qt5/mkspecs/features/testcase_targets.prf \
		/home/tommy/raspi/qt5/mkspecs/features/exceptions.prf \
		/home/tommy/raspi/qt5/mkspecs/features/yacc.prf \
		/home/tommy/raspi/qt5/mkspecs/features/lex.prf \
		ModbusTest.pro helpers.h \
		modbus.h \
		modbusbase.h \
		modbusdatatable.h \
		modbushandler.h \
		modbusmaster.h \
		modbusslave.h helpers.cpp \
		main.cpp \
		modbus.cpp \
		modbusbase.cpp \
		modbusdatatable.cpp \
		modbushandler.cpp \
		modbusmaster.cpp \
		modbusslave.cpp
QMAKE_TARGET  = ModbusTest
DESTDIR       = 
TARGET        = ModbusTest


first: all
####### Build rules

ModbusTest:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ModbusTest.pro /home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf /home/tommy/raspi/qt5/mkspecs/features/spec_pre.prf \
		/home/tommy/raspi/qt5/mkspecs/common/unix.conf \
		/home/tommy/raspi/qt5/mkspecs/common/linux.conf \
		/home/tommy/raspi/qt5/mkspecs/common/sanitize.conf \
		/home/tommy/raspi/qt5/mkspecs/common/gcc-base.conf \
		/home/tommy/raspi/qt5/mkspecs/common/gcc-base-unix.conf \
		/home/tommy/raspi/qt5/mkspecs/common/g++-base.conf \
		/home/tommy/raspi/qt5/mkspecs/common/g++-unix.conf \
		/home/tommy/raspi/qt5/mkspecs/qdevice.pri \
		/home/tommy/raspi/qt5/mkspecs/features/device_config.prf \
		/home/tommy/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf \
		/home/tommy/raspi/qt5/mkspecs/devices/common/linux_device_post.conf \
		/home/tommy/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf \
		/home/tommy/raspi/qt5/mkspecs/qconfig.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_freetype.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_libjpeg.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_libpng.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_core.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_gui.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_network.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_sql.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_xml.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/home/tommy/raspi/qt5/mkspecs/features/qt_functions.prf \
		/home/tommy/raspi/qt5/mkspecs/features/qt_config.prf \
		/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf \
		/home/tommy/raspi/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/tommy/raspi/qt5/mkspecs/features/exclusive_builds.prf \
		/home/tommy/raspi/qt5/mkspecs/features/toolchain.prf \
		/home/tommy/raspi/qt5/mkspecs/features/default_pre.prf \
		/home/tommy/raspi/qt5/mkspecs/features/resolve_config.prf \
		/home/tommy/raspi/qt5/mkspecs/features/default_post.prf \
		/home/tommy/raspi/qt5/mkspecs/features/warn_on.prf \
		/home/tommy/raspi/qt5/mkspecs/features/qt.prf \
		/home/tommy/raspi/qt5/mkspecs/features/resources_functions.prf \
		/home/tommy/raspi/qt5/mkspecs/features/resources.prf \
		/home/tommy/raspi/qt5/mkspecs/features/moc.prf \
		/home/tommy/raspi/qt5/mkspecs/features/unix/thread.prf \
		/home/tommy/raspi/qt5/mkspecs/features/qmake_use.prf \
		/home/tommy/raspi/qt5/mkspecs/features/file_copies.prf \
		/home/tommy/raspi/qt5/mkspecs/features/testcase_targets.prf \
		/home/tommy/raspi/qt5/mkspecs/features/exceptions.prf \
		/home/tommy/raspi/qt5/mkspecs/features/yacc.prf \
		/home/tommy/raspi/qt5/mkspecs/features/lex.prf \
		ModbusTest.pro
	$(QMAKE) -o Makefile ModbusTest.pro
/home/tommy/raspi/qt5/mkspecs/features/spec_pre.prf:
/home/tommy/raspi/qt5/mkspecs/common/unix.conf:
/home/tommy/raspi/qt5/mkspecs/common/linux.conf:
/home/tommy/raspi/qt5/mkspecs/common/sanitize.conf:
/home/tommy/raspi/qt5/mkspecs/common/gcc-base.conf:
/home/tommy/raspi/qt5/mkspecs/common/gcc-base-unix.conf:
/home/tommy/raspi/qt5/mkspecs/common/g++-base.conf:
/home/tommy/raspi/qt5/mkspecs/common/g++-unix.conf:
/home/tommy/raspi/qt5/mkspecs/qdevice.pri:
/home/tommy/raspi/qt5/mkspecs/features/device_config.prf:
/home/tommy/raspi/qt5/mkspecs/devices/common/linux_device_pre.conf:
/home/tommy/raspi/qt5/mkspecs/devices/common/linux_device_post.conf:
/home/tommy/raspi/qt5/mkspecs/devices/common/linux_arm_device_post.conf:
/home/tommy/raspi/qt5/mkspecs/qconfig.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_freetype.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_libjpeg.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_ext_libpng.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_core.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_core_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_dbus.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_gui.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_network.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_network_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_opengl.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_serialport.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_sql.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_testlib.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_widgets.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_xml.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/home/tommy/raspi/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/home/tommy/raspi/qt5/mkspecs/features/qt_functions.prf:
/home/tommy/raspi/qt5/mkspecs/features/qt_config.prf:
/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++/qmake.conf:
/home/tommy/raspi/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/tommy/raspi/qt5/mkspecs/features/exclusive_builds.prf:
/home/tommy/raspi/qt5/mkspecs/features/toolchain.prf:
/home/tommy/raspi/qt5/mkspecs/features/default_pre.prf:
/home/tommy/raspi/qt5/mkspecs/features/resolve_config.prf:
/home/tommy/raspi/qt5/mkspecs/features/default_post.prf:
/home/tommy/raspi/qt5/mkspecs/features/warn_on.prf:
/home/tommy/raspi/qt5/mkspecs/features/qt.prf:
/home/tommy/raspi/qt5/mkspecs/features/resources_functions.prf:
/home/tommy/raspi/qt5/mkspecs/features/resources.prf:
/home/tommy/raspi/qt5/mkspecs/features/moc.prf:
/home/tommy/raspi/qt5/mkspecs/features/unix/thread.prf:
/home/tommy/raspi/qt5/mkspecs/features/qmake_use.prf:
/home/tommy/raspi/qt5/mkspecs/features/file_copies.prf:
/home/tommy/raspi/qt5/mkspecs/features/testcase_targets.prf:
/home/tommy/raspi/qt5/mkspecs/features/exceptions.prf:
/home/tommy/raspi/qt5/mkspecs/features/yacc.prf:
/home/tommy/raspi/qt5/mkspecs/features/lex.prf:
ModbusTest.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ModbusTest.pro

qmake_all: FORCE


all: Makefile ModbusTest

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/tommy/raspi/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents helpers.h modbus.h modbusbase.h modbusdatatable.h modbushandler.h modbusmaster.h modbusslave.h $(DISTDIR)/
	$(COPY_FILE) --parents helpers.cpp main.cpp modbus.cpp modbusbase.cpp modbusdatatable.cpp modbushandler.cpp modbusmaster.cpp modbusslave.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/tommy/raspi/qt5/mkspecs/features/data/dummy.cpp
	/opt/cross-pi-gcc/bin/arm-linux-gnueabihf-g++ -pipe -marm -mfpu=vfp -mtune=arm1176jzf-s -march=armv6zk -mabi=aapcs-linux -mfloat-abi=hard --sysroot=/home/tommy/raspi/sysroot -O2 -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /home/tommy/raspi/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_modbus.cpp moc_modbusbase.cpp moc_modbusdatatable.cpp moc_modbushandler.cpp moc_modbusslave.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_modbus.cpp moc_modbusbase.cpp moc_modbusdatatable.cpp moc_modbushandler.cpp moc_modbusslave.cpp
moc_modbus.cpp: modbus.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		moc_predefs.h \
		/home/tommy/raspi/qt5/bin/moc
	/home/tommy/raspi/qt5/bin/moc $(DEFINES) --include /mnt/d/_Work/ModbusTest/moc_predefs.h -I/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/mnt/d/_Work/ModbusTest -I/home/tommy/raspi/qt5pi/include -I/home/tommy/raspi/qt5pi/include/QtNetwork -I/home/tommy/raspi/qt5pi/include/QtCore -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0 -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/arm-linux-gnueabihf -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/backward -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include-fixed -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include modbus.h -o moc_modbus.cpp

moc_modbusbase.cpp: modbusbase.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		modbusdatatable.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		moc_predefs.h \
		/home/tommy/raspi/qt5/bin/moc
	/home/tommy/raspi/qt5/bin/moc $(DEFINES) --include /mnt/d/_Work/ModbusTest/moc_predefs.h -I/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/mnt/d/_Work/ModbusTest -I/home/tommy/raspi/qt5pi/include -I/home/tommy/raspi/qt5pi/include/QtNetwork -I/home/tommy/raspi/qt5pi/include/QtCore -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0 -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/arm-linux-gnueabihf -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/backward -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include-fixed -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include modbusbase.h -o moc_modbusbase.cpp

moc_modbusdatatable.cpp: modbusdatatable.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		moc_predefs.h \
		/home/tommy/raspi/qt5/bin/moc
	/home/tommy/raspi/qt5/bin/moc $(DEFINES) --include /mnt/d/_Work/ModbusTest/moc_predefs.h -I/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/mnt/d/_Work/ModbusTest -I/home/tommy/raspi/qt5pi/include -I/home/tommy/raspi/qt5pi/include/QtNetwork -I/home/tommy/raspi/qt5pi/include/QtCore -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0 -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/arm-linux-gnueabihf -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/backward -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include-fixed -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include modbusdatatable.h -o moc_modbusdatatable.cpp

moc_modbushandler.cpp: modbushandler.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		modbusmaster.h \
		modbusbase.h \
		modbusdatatable.h \
		helpers.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString \
		modbusslave.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QtMath \
		/home/tommy/raspi/qt5pi/include/QtCore/qmath.h \
		moc_predefs.h \
		/home/tommy/raspi/qt5/bin/moc
	/home/tommy/raspi/qt5/bin/moc $(DEFINES) --include /mnt/d/_Work/ModbusTest/moc_predefs.h -I/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/mnt/d/_Work/ModbusTest -I/home/tommy/raspi/qt5pi/include -I/home/tommy/raspi/qt5pi/include/QtNetwork -I/home/tommy/raspi/qt5pi/include/QtCore -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0 -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/arm-linux-gnueabihf -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/backward -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include-fixed -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include modbushandler.h -o moc_modbushandler.cpp

moc_modbusslave.cpp: modbusslave.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString \
		/home/tommy/raspi/qt5pi/include/QtCore/QtMath \
		/home/tommy/raspi/qt5pi/include/QtCore/qmath.h \
		helpers.h \
		modbusbase.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		modbusdatatable.h \
		moc_predefs.h \
		/home/tommy/raspi/qt5/bin/moc
	/home/tommy/raspi/qt5/bin/moc $(DEFINES) --include /mnt/d/_Work/ModbusTest/moc_predefs.h -I/home/tommy/raspi/qt5/mkspecs/devices/linux-rasp-pi-g++ -I/mnt/d/_Work/ModbusTest -I/home/tommy/raspi/qt5pi/include -I/home/tommy/raspi/qt5pi/include/QtNetwork -I/home/tommy/raspi/qt5pi/include/QtCore -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0 -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/arm-linux-gnueabihf -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include/c++/10.1.0/backward -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include -I/opt/cross-pi-gcc/lib/gcc/arm-linux-gnueabihf/10.1.0/include-fixed -I/opt/cross-pi-gcc/arm-linux-gnueabihf/include modbusslave.h -o moc_modbusslave.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

helpers.o: helpers.cpp helpers.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpers.o helpers.cpp

main.o: main.cpp /home/tommy/raspi/qt5pi/include/QtCore/QCoreApplication \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreapplication.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qeventloop.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		modbus.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		modbusslave.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString \
		/home/tommy/raspi/qt5pi/include/QtCore/QtMath \
		/home/tommy/raspi/qt5pi/include/QtCore/qmath.h \
		helpers.h \
		modbusbase.h \
		modbusdatatable.h \
		modbusmaster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

modbus.o: modbus.cpp modbus.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbus.o modbus.cpp

modbusbase.o: modbusbase.cpp modbusbase.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		modbusdatatable.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusbase.o modbusbase.cpp

modbusdatatable.o: modbusdatatable.cpp modbusdatatable.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusdatatable.o modbusdatatable.cpp

modbushandler.o: modbushandler.cpp modbushandler.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		modbusmaster.h \
		modbusbase.h \
		modbusdatatable.h \
		helpers.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString \
		modbusslave.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QtMath \
		/home/tommy/raspi/qt5pi/include/QtCore/qmath.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbushandler.o modbushandler.cpp

modbusmaster.o: modbusmaster.cpp modbusmaster.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		modbusbase.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		modbusdatatable.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		helpers.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusmaster.o modbusmaster.cpp

modbusslave.o: modbusslave.cpp modbusslave.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QDebug \
		/home/tommy/raspi/qt5pi/include/QtCore/qdebug.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobal.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig-bootstrapped.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qconfig.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtcore-config.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsystemdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qprocessordetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcompilerdetection.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtypeinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsysinfo.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlogging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qflags.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbasicatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_bootstrap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qgenericatomic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_cxx11.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qatomic_msvc.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qglobalstatic.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmutex.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnumeric.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qversiontagging.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhash.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qchar.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiterator.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qrefcount.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qarraydata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qhashfunctions.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstring.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qnamespace.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringliteral.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringalgorithms.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringview.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringbuilder.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpair.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvector.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainertools_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qpoint.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qbytearraylist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringlist.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qregexp.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qstringmatcher.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmap.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qtextstream.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qiodevice.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobjectdefs_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcoreevent.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qscopedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qmetatype.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvarlengtharray.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontainerfwd.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qobject_impl.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qlocale.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qvariant.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qshareddata.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qset.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qcontiguouscache.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer.h \
		/home/tommy/raspi/qt5pi/include/QtCore/qsharedpointer_impl.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpSocket \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetworkglobal.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtnetwork-config.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qabstractsocket.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/QTcpServer \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qtcpserver.h \
		/home/tommy/raspi/qt5pi/include/QtNetwork/qhostaddress.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QString \
		/home/tommy/raspi/qt5pi/include/QtCore/QtMath \
		/home/tommy/raspi/qt5pi/include/QtCore/qmath.h \
		helpers.h \
		modbusbase.h \
		/home/tommy/raspi/qt5pi/include/QtCore/QObject \
		modbusdatatable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o modbusslave.o modbusslave.cpp

moc_modbus.o: moc_modbus.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbus.o moc_modbus.cpp

moc_modbusbase.o: moc_modbusbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbusbase.o moc_modbusbase.cpp

moc_modbusdatatable.o: moc_modbusdatatable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbusdatatable.o moc_modbusdatatable.cpp

moc_modbushandler.o: moc_modbushandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbushandler.o moc_modbushandler.cpp

moc_modbusslave.o: moc_modbusslave.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_modbusslave.o moc_modbusslave.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ModbusTest/bin || mkdir -p $(INSTALL_ROOT)/opt/ModbusTest/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/ModbusTest/bin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/opt/ModbusTest/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/ModbusTest/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ModbusTest/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

